import type { Metadata } from "next";
import { Hind, Inter, Montserrat, Pontano_Sans } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";

const hind = Hind({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-hind",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-display",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${montserrat.variable} ${hind.className}  scroll-smooth`}>
      <body className={"leading-loose"}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
